
columns:
    id: int
    Gender: object
    Age: int
    Driving_License: int
    Region_Code: float
    Previously_Insured: int
    Vehicle_Age: object
    Vehicle_Damage: object
    Annual_Premium: float
    Policy_Sales_Channel: float
    Vintage: int

target_column:
    target: Response